# Generated by Django 3.2.6 on 2021-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20210828_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestpoint',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='interestpoint',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
