# Generated by Django 3.2.6 on 2021-08-29 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0004_auto_20210829_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedinterest',
            name='shared_user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
